# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Medusal
email: contact@medusal.com
description: > # this means to ignore newlines until "baseurl:"
  Pour une prise en charge connectée
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://medusal.github.io" # the base hostname & protocol for your site
twitter_username: GetMedusal

# Build settings
markdown: kramdown
include: ['_pages']

defaults:
  -
    scope:
      type: pages
    values:
      layout: "default"
      nav_name: null
      footer_name: null
      excerpt: null
      color: null
      weight: 10
      permalink: null
  -
    scope:
      type: posts
    values:
      layout: "default"
      excerpt: ''
      banner: null
      categories: []
      tags: []
      author: 'Yacine Sedrati'
      permalink: '/blog/:categories/:slug/'
      color: '#A33D62'
months:
  - janvier
  - février
  - mars
  - avril
  - mai
  - juin
  - juillet
  - août
  - septembre
  - octobre
  - novembre
  - décembre
